version: '3'

services:
  # app
  auth-service:
#    platform: 'linux/amd64'
    image: 'auth-service:latest'
    container_name: auth-service
    build:
      context: auth-service
      dockerfile: Dockerfile
    depends_on:
      - user-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=capstone
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8081
    expose:
      - "8081"
    ports:
      - "8081:8081"
  management-user-service:
#    platform: 'linux/amd64'
    image: 'management-user-service:latest'
    container_name: management-user-service
    build:
      context: management-user-service
      dockerfile: Dockerfile
    depends_on:
      - user-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=capstone
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8082
    expose:
      - "8082"
    ports:
      - "8082:8082"
  item-service:
#    platform: 'linux/amd64'
    image: 'item-service:latest'
    container_name: item-service
    build:
      context: item-service
      dockerfile: Dockerfile
    depends_on:
      - request-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://request-db:3306/request_db
      - SPRING_DATASOURCE_USERNAME=capstone
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8083
    expose:
      - "8083"
    ports:
      - "8083:8083"
  request-service:
#    platform: 'linux/amd64'
    image: 'request-service:latest'
    container_name: request-service
    build:
      context: request-service
      dockerfile: Dockerfile
    depends_on:
      - request-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://request-db:3306/request_db
      - SPRING_DATASOURCE_USERNAME=capstone
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8084
    expose:
      - "8084"
    ports:
      - "8084:8084"
  # database 
  user-db:
    image: 'postgres:15-alpine'
    container_name: user-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=capstone
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=user_db
    volumes:
      - user_db:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
  request-db:
    image: mysql:latest
    container_name: request-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: capstone
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: request_db
    volumes:
      - request_db:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
      
volumes:
  user_db:
  request_db:


