#get all request type
GET http://localhost:8084/v1/api/requesttypes
Accept: application/json

###
#get request type by uuid
GET http://localhost:8084/v1/api/requesttypes/4400e94b-aae6-47f7-9b4e-141d92fbdaa1
Accept: application/json

###
#get all request
GET http://localhost:8084/v1/api/requests
Accept: application/json

###
#get request by uuid
GET http://localhost:8084/v1/api/requests/4400e94b-aae6-47f7-9b4e-141d92fbdaa1
Accept: application/json

###
#add request
POST http://localhost:8084/v1/api/requests
Content-Type: application/json
Authorization: bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoibnVtYW5hcmlmIiwiZXhwIjoxNjc5MDUyNDYxLCJpYXQiOjE2NzkwNDg4NjEsInNjb3BlIjoiIn0.ASnA7z49W87lflb_efpho6w6gjacd9ipDEcFHQt8uY-3Gux2Bk2i8r698QGwqnVjUDgYVQJT0WUI2uD4rTWLmI7aY8JRGp1MhTKHPpfoM2Pe4zkTGxw_ba-VcmrCjlXr_KrMyzXAuylVIkSrCH9bJpAHpGQ3FRbXupDDp9hAq9SonfqpLVETUEG8Bm-tx_ZV3zmn2h-xQSpUT_xlYqQAeKuTsi6lPx18siQ5X7zrYbsURKeHRU8O4fTkhl9t26rWwta4oBMeOn_r_VB3KY1rXeGtrAaHavv60QLvde4R6c3hyo6qcm5BwM1VmNl8PScs69SJmyzeZadewK0pD_DEfA

{
  "header": {
    "typeUuid": "35f72873-6284-4a07-b4db-265439f6ea30",
    "description": "test request tipe item 1"
  },
  "details": [
    {
      "itemUuid": "f4ffd41c-a7ca-4512-bfd7-0098d00e9866",
      "serviceUuid": "",
      "qty": 4,
      "price": 9000000,
      "desc": "test item 1"
    }

  ]
}
###
#Delete requset by uuid
DELETE http://localhost:8084/v1/api/requests/9e5830c5-9e12-432e-90af-613632546aba
Accept: application/json

###

###
#update request type by uuid
PUT http://localhost:8084/v1/api/requests/95d8fb23-4477-446e-9b26-ee784fa28b69
Content-Type: application/json
Authorization: bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiU1VQRVJBRE1JTiIsImV4cCI6MTY3ODQ2NDc4MCwiaWF0IjoxNjc4NDYxMTgwLCJzY29wZSI6IiJ9.puM864AW6LuAGH45P-7JuCtUTbdkfMUo4Dlck_T4S8pkxAcOwHNaag4Lktk3o6H-qd8XO-h1UBmL5Mot3hPO5GIi1F_g-pli3DgB7M_Fo7aFEBS-C9M4khuR1An52OCNggt4assdtjaXV-Tu5_Rj3HXdkKWgqqA7StCgv4GAd-CirqXeIorkdTEd8edM8yA8KAN-mj2S_6Vr4VQvEcF1Ytcjf2ZpT4opmmHci-NP2LkkS3LQ96JH7WgRzSLg1w3qqeMxw63I_s8MQJ4VRVlXrAdODzeWoYDUP0WRGEpHUsjbey4uQejNfP8-gD6wx9WYcEI-5JFalmiFdrsRbakjqw

{
  "typeUuid": "e31424dc-3264-4c2a-9be6-c73bb8e3acb3",
  "description": "testing updated"
}

###
#add detail
POST http://localhost:8084/v1/api/request-details
Content-Type: application/json

{
  "desc": "string",
  "itemUuid": "ae18d913-db43-43d0-ad17-4174f3ee992f",
  "price": 1,
  "qty": 8000000.0,
  "requestUuid": "30a4cb83-522a-4721-be0d-afe4d49bd06a",
  "serviceUuid": ""
}

###
#Delete detail by uuid
DELETE http://localhost:8084/v1/api/request-details/86f215d0-06de-4f18-9e68-c9c98b8845a3
Accept: application/json

###
#get detail by uuid
GET http://localhost:8084/v1/api/request-details/ccf5d753-451e-4147-88d7-d2314e5d3ce1
Accept: application/json

###