POST localhost:8081/api/v1/auth/register
Content-Type: application/json

{
  "username" : "numanarif",
  "email" : "admin@ikon.com",
  "password" : "Abcd@1234",
  "name" : "numanarif",
  "role" : "ADMIN",
  "department" : "HRD"
}

###

POST localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "username" : "numanarif",
  "password" : "numanarif@123"
}

> {%
client.global.set("token", response.body.data);
%}
###

GET localhost:8081/api/v1/auth/user-data
Authorization: Bearer {{token}}
