POST localhost:8081/api/v1/auth/register
Content-Type: application/json

{
  "username" : "numanarif",
  "email" : "admin@ikon.com",
  "password" : "Abcd@1234",
  "name" : "numanarif",
  "role" : "ADMIN",
  "department" : "HRD"
}

###

POST localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "username" : "SUPERADMIN",
  "password" : "12345678"
}

> {%
client.global.set("token", response.body.data);
%}
###

GET localhost:8081/api/v1/auth/user-data/username-dept
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiU1VQRVJBRE1JTiIsImV4cCI6MTY3ODg2ODg2MiwiaWF0IjoxNjc4ODY1MjYyLCJzY29wZSI6IiJ9.k_lINp1AJlJBNHuxUZ1CQmtZnDWYxcPRYCs4-DjcvFdPvek5JM0VsO1hyCxRmbjCW3VGTTkgIzZ73jsjMN5YdMNjMHin7RVRuO8d3upjMYutEQxg1mEVxTRKsEbFdmn2mBZyFAumYnTg9XYXWGHnTvMNuKtFSkdYUI_c9PWBthj9Iez3RvFnEUPRxt-Pkc7EgaScNuU2bzf5KkMZNX3CLR8e8KQTlpT8luFIKkkxcvobHEjWCp9n-YxNrm5M-IBQZCJnsHXR5I6VHRy-6HKSJF0ON3nCEhZJl1rwAzMk1LnMs58qb00St7n0ZgMHp5ddgAezN_gk8r06GN2XjhuJGQ
