POST http://localhost:8082/v1/api/users
Content-Type: application/json

{
  "username": "irfanset",
  "email": "irfanset@gmail.com",
  "password": "irfanset123",
  "active": true,
  "createdby": "system",
  "lastupdatedby": "system"
}

###
