# add user endpoint
POST http://localhost:8082/v1/api/users
Content-Type: application/json

{
  "username": "irfanset",
  "email": "irfanset@gmail.com",
  "password": "irfanset123",
  "active": true,
  "createdby": "system",
  "lastupdatedby": "system"
}

###
# get user by uuid
GET http://localhost:8082/v1/api/users/32f2fcb3-bb48-4341-8d25-233ea4690dae
Content-Type: application/json

###
#get all roles
GET http://localhost:8082/v1/api/users/roles
Content-Type: application/json

###
#get roles by uuid
GET http://localhost:8082/v1/api/users/roles/32f2fcb3-bb48-4342-8d25-233ea4690dae
Content-Type: application/json

###
#get all departments
GET http://localhost:8082/v1/api/users/departments
Content-Type: application/json

###
#get departments by uuid
GET http://localhost:8082/v1/api/users/departments/67g2fcb3-bb48-4341-8d25-233ea4690dae
Content-Type: application/json

###
# add user role
POST http://localhost:8082/v1/api/users/roles
Content-Type: application/json

{
  "useruuid": "32f2fcb3-bb48-4341-8d25-233ea4690dae",
  "roleuuid": "78f2fcb3-bb48-4342-8d25-233ea4690dae"
}