POST http://localhost:8082/v1/api/users
Content-Type: application/json

{
  "username": "irfanset",
  "email": "irfanset@gmail.com",
  "password": "irfanset123",
  "active": true,
  "createdby": "system",
  "lastupdatedby": "system"
}

###
GET http://localhost:8082/v1/api/users/32f2fcb3-bb48-4341-8d25-233ea4690dae
Content-Type: application/json

###
GET http://localhost:8082/v1/api/users/roles
Content-Type: application/json
