name: CI/CD development

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#      - name: Delete local .m2 repository
#        run: rm -rf ~/.m2/repository

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete directory target
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_INSTANCE_HOST }}
          username: ${{ secrets.EC2_INSTANCE_NAME }}
          password: ${{ secrets.EC2_INSTANCE_PASSWORD }}
          script: |
            cd ~/
            rm -rf capstone-backend
        
      - name: Copy files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_HOST }}
          username: ${{ secrets.EC2_INSTANCE_NAME }}
          password: ${{ secrets.EC2_INSTANCE_PASSWORD }}
          source: ./
          target: ~/capstone-backend

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_INSTANCE_HOST }}
          username: ${{ secrets.EC2_INSTANCE_NAME }}
          password: ${{ secrets.EC2_INSTANCE_PASSWORD }}
          script: |
            cd ~/capstone-backend
            docker compose down
            chmod u+x remove_images.sh
            ./remove_images.sh
            docker compose up -d
